/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import gaussseidel.modelos.FormulasGaussSeidel;
import controladores.OyenteBotones;

/**
 *
 * @author jarv
 */
public class PanelGaussSeidel extends javax.swing.JPanel {

    /**
     * Creates new form PanelMetodoGaussSeidel
     */
    public PanelGaussSeidel() {
        initComponents();
        FormulasGaussSeidel formulas = new FormulasGaussSeidel();
        OyenteBotones controlador = new OyenteBotones(formulas, this);
        addEventos(controlador);
    }
    
    private final void addEventos(OyenteBotones controlador) {
        botonCalcularValores.addActionListener(controlador);
        botonEstablecerTamano.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCampos = new javax.swing.JPanel();
        panelTamanoMatriz = new javax.swing.JPanel();
        tamanoLabel = new javax.swing.JLabel();
        campoFilas = new javax.swing.JTextField();
        multiploLabel = new javax.swing.JLabel();
        campoColumnas = new javax.swing.JTextField();
        botonEstablecerTamano = new javax.swing.JButton();
        panelTolerancia = new javax.swing.JPanel();
        toleranciaLabel = new javax.swing.JLabel();
        campoTolerancia = new javax.swing.JTextField();
        panelesTablas = new javax.swing.JTabbedPane();
        panelIntroducir = new javax.swing.JPanel();
        panelVector = new javax.swing.JPanel();
        panelVectorInicial = new javax.swing.JScrollPane();
        tablaVectorInicial = new javax.swing.JTable();
        panelIntroducirMatriz = new javax.swing.JPanel();
        panelMatriz = new javax.swing.JScrollPane();
        tablaMatriz = new javax.swing.JTable();
        panelResultados = new javax.swing.JPanel();
        panelTablaResultados = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        botonCalcularValores = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 15));
        setLayout(new java.awt.BorderLayout());

        panelCampos.setLayout(new java.awt.GridLayout(2, 1));

        panelTamanoMatriz.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tamanoLabel.setText("Tamaño de Matriz:");
        panelTamanoMatriz.add(tamanoLabel);

        campoFilas.setColumns(3);
        panelTamanoMatriz.add(campoFilas);

        multiploLabel.setText("X");
        panelTamanoMatriz.add(multiploLabel);

        campoColumnas.setColumns(3);
        panelTamanoMatriz.add(campoColumnas);

        botonEstablecerTamano.setText("Establecer Tamaño");
        botonEstablecerTamano.setName("botonEstablecerTamano"); // NOI18N
        panelTamanoMatriz.add(botonEstablecerTamano);

        panelCampos.add(panelTamanoMatriz);

        panelTolerancia.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        toleranciaLabel.setText("Tolerancia:");
        panelTolerancia.add(toleranciaLabel);

        campoTolerancia.setColumns(8);
        panelTolerancia.add(campoTolerancia);

        panelCampos.add(panelTolerancia);

        add(panelCampos, java.awt.BorderLayout.NORTH);

        panelIntroducir.setLayout(new java.awt.GridLayout(2, 0));

        panelVector.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores para Vector Inicial", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelVector.setLayout(new java.awt.GridLayout(1, 0));

        tablaVectorInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaVectorInicial.setGridColor(new java.awt.Color(160, 160, 160));
        tablaVectorInicial.setShowGrid(true);
        panelVectorInicial.setViewportView(tablaVectorInicial);

        panelVector.add(panelVectorInicial);

        panelIntroducir.add(panelVector);

        panelIntroducirMatriz.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores para Matriz de Tamaño NxN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelIntroducirMatriz.setLayout(new java.awt.GridLayout(1, 0));

        tablaMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaMatriz.setGridColor(new java.awt.Color(160, 160, 160));
        tablaMatriz.setShowGrid(true);
        panelMatriz.setViewportView(tablaMatriz);

        panelIntroducirMatriz.add(panelMatriz);

        panelIntroducir.add(panelIntroducirMatriz);

        panelesTablas.addTab("Introducir Valores", panelIntroducir);

        panelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelResultados.setLayout(new java.awt.GridLayout(1, 0));

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Xi", "Ea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaResultados.setGridColor(new java.awt.Color(160, 160, 160));
        tablaResultados.setShowGrid(true);
        panelTablaResultados.setViewportView(tablaResultados);

        panelResultados.add(panelTablaResultados);

        panelesTablas.addTab("Resultados", panelResultados);

        add(panelesTablas, java.awt.BorderLayout.CENTER);

        botonCalcularValores.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        botonCalcularValores.setText("Calcular Valores");
        botonCalcularValores.setName("botonCalcularValores"); // NOI18N
        botonCalcularValores.setPreferredSize(new java.awt.Dimension(155, 40));
        add(botonCalcularValores, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    
    public javax.swing.JTable getVectorInicial() {
        return tablaVectorInicial;
    }
    
    public javax.swing.JTable getTablaMatriz() {
        return tablaMatriz;
    }
    
    public javax.swing.JTable getTablaResultados() {
        return tablaResultados;
    }
    
    public javax.swing.JTextField getCampoColumnas() {
        return campoColumnas;
    }
    
    public javax.swing.JTextField getCampoFilas() {
        return campoFilas;
    }
    
    public javax.swing.JTextField getCampoToleancia() {
        return campoTolerancia;
    }
    
    public javax.swing.JTabbedPane getPanelesTablas() {
        return panelesTablas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcularValores;
    private javax.swing.JButton botonEstablecerTamano;
    private javax.swing.JTextField campoColumnas;
    private javax.swing.JTextField campoFilas;
    private javax.swing.JTextField campoTolerancia;
    private javax.swing.JLabel multiploLabel;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelIntroducir;
    private javax.swing.JPanel panelIntroducirMatriz;
    private javax.swing.JScrollPane panelMatriz;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JScrollPane panelTablaResultados;
    private javax.swing.JPanel panelTamanoMatriz;
    private javax.swing.JPanel panelTolerancia;
    private javax.swing.JPanel panelVector;
    private javax.swing.JScrollPane panelVectorInicial;
    private javax.swing.JTabbedPane panelesTablas;
    private javax.swing.JTable tablaMatriz;
    private javax.swing.JTable tablaResultados;
    private javax.swing.JTable tablaVectorInicial;
    private javax.swing.JLabel tamanoLabel;
    private javax.swing.JLabel toleranciaLabel;
    // End of variables declaration//GEN-END:variables
}
